/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tarde
 */
public class Cliente extends javax.swing.JFrame {

    ArrayList<ClientePOJO> clientes = leerDatos();
    int contador = clientes.size();

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagen-por-defecto(1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 250, 190));

        jButton1.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jButton1.setText("Inserte una fotografía aquí");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 200, -1));

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton2.setText("Retiro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 180, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 470, 280));

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton3.setText("Crear Cuenta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 40));

        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton4.setText("Depósito");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String nombreUser = JOptionPane.showInputDialog(this, "Ingrese su nombre:", "Deposito", JOptionPane.QUESTION_MESSAGE);
        String ingreso = JOptionPane.showInputDialog(this, "Cuanto quiere depositar:", "Deposito", JOptionPane.QUESTION_MESSAGE);
        double ingresoD = Double.parseDouble(ingreso);
        for (ClientePOJO cliente : clientes) {
            if (cliente.getNombre().equals(nombreUser)) {
                cliente.setSaldo(ingresoD + cliente.getSaldo());
            }
        }
        actualizarTabla();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code her
        String nombre = JOptionPane.showInputDialog(this, "Ingrese su nombre:", "Datos del usuario", JOptionPane.QUESTION_MESSAGE);
        String ingresoInicial = JOptionPane.showInputDialog(this, "Ingrese un saldo inicial:", "Datos del usuario", JOptionPane.QUESTION_MESSAGE);
        double ingreso = Double.parseDouble(ingresoInicial);
        System.out.println(nombre);
        System.out.println(ingreso);
        ClientePOJO cliente = new ClientePOJO(contador, nombre, ingreso);
        this.clientes.add(cliente);

        actualizarTabla();
        this.contador++;

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombreUser = JOptionPane.showInputDialog(this, "Ingrese su nombre:", "Retiro", JOptionPane.QUESTION_MESSAGE);
        String retiro = JOptionPane.showInputDialog(this, "Cuanto quiere retirar:", "Retiro", JOptionPane.QUESTION_MESSAGE);
        double retiroD = Double.parseDouble(retiro);
        for (ClientePOJO cliente : clientes) {
            if (cliente.getNombre().equals(nombreUser)) {
                if (cliente.getSaldo() - retiroD >= 0) {
                    cliente.setSaldo(cliente.getSaldo() - retiroD);
                } else {
                    JOptionPane.showMessageDialog(this, "No dispone de suficientes fondos para retirar!!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        actualizarTabla();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione una imagen");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif"));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {

                ImageIcon originalImage = new ImageIcon(selectedFile.getAbsolutePath());

                Image scaledImage = originalImage.getImage().getScaledInstance(
                        jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);

                jLabel9.setIcon(new ImageIcon(scaledImage));
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void actualizarTabla() {
        

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (ClientePOJO cliente : clientes) {

            model.addRow(new Object[]{cliente.getId(), cliente.getNombre(), cliente.getSaldo()});
        }

    }

    private ArrayList<ClientePOJO> leerDatos() {

        File f = new File("cuentas.txt");
        if (!f.exists()) {
            System.out.println("El archivo no existe: " + f.getAbsolutePath());
            return new ArrayList<>();
        }
        ArrayList<ClientePOJO> usuarios = new ArrayList<>();

        try (BufferedReader bfr = new BufferedReader(new FileReader(f))) {
            String linea = "";

            while ((linea = bfr.readLine()) != null) {
                String[] partes = linea.split(" ");
                ClientePOJO nuevo = new ClientePOJO(Integer.parseInt(partes[0]), partes[1], Double.parseDouble(partes[2]));
                usuarios.add(nuevo);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        return usuarios;
    }
}
